<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.9" />
    <PackageReference Include="Ninject" Version="3.3.6" />
    <PackageReference Include="System.Data.SQLite" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameStore.BusinessLogic\GameStore.BusinessLogic.csproj" />
    <ProjectReference Include="..\GameStore.DataAccessLayer\GameStore.DataAccessLayer.csproj" />
    <ProjectReference Include="..\GameStore.Entity\GameStore.Entity.csproj" />
  </ItemGroup>

</Project>