<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EmployeeApp.Core\EmployeeApp.Core.csproj" />
    <ProjectReference Include="..\EmployeeApp.Data\EmployeeApp.Data.csproj" />
  </ItemGroup>

</Project>
